[tool.poetry]
name = "fe-awakening"
version = "0.1.0"
description = "Fire Emblem Awakening Skill and Class Network for Character Optimization"
authors = ["Nick Anthony <nanthony007@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
black = "^20.8b1"
pytest = "^6.1.1"
requests = "^2.24.0"
bs4 = "^0.0.1"
ipython = "^7.18.1"
pydantic = "^1.6.1"
pandas = "^1.1.3"
neo4j = "^4.1.1"
py2neo = "^2020.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
